#############################################################################
# Makefile for building: particle\ system.app/Contents/MacOS/particle\ system
# Generated by qmake (3.1) (Qt 5.10.0)
# Project:  particle system.pro
# Template: app
# Command: /private/tmp/5.10.0/clang_64/bin/qmake -o Makefile particle\ system.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers -I/private/tmp/5.10.0/clang_64/lib/QtGui.framework/Headers -I/private/tmp/5.10.0/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I/private/tmp/5.10.0/clang_64/mkspecs/macx-clang -F/private/tmp/5.10.0/clang_64/lib
QMAKE         = /private/tmp/5.10.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /private/tmp/5.10.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /private/tmp/5.10.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = particle\ system1.0.0
DISTDIR = /Users/vpopovyc/workspace/particle\ system/.tmp/particle\ system1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/private/tmp/5.10.0/clang_64/lib
LIBS          = $(SUBLIBS) -F/private/tmp/5.10.0/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = App.cpp \
		main.cpp moc_App.cpp
OBJECTS       = App.o \
		main.o \
		moc_App.o
DIST          = /private/tmp/5.10.0/clang_64/mkspecs/features/spec_pre.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/qdevice.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/features/device_config.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/unix.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/mac.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/macx.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/sanitize.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/gcc-base.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/clang.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/clang-mac.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/qconfig.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/features/qt_functions.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/qt_config.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/private/tmp/5.10.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/sdk.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/toolchain.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/toolchain.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/default_pre.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/resolve_config.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/default_post.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/default_post.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/mac.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/warn_on.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/qt.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/resources.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/moc.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/unix/opengl.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/uic.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/unix/thread.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/qmake_use.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/file_copies.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/rez.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/testcase_targets.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/exceptions.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/yacc.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/lex.prf \
		particle system.pro App.hpp App.cpp \
		main.cpp
QMAKE_TARGET  = particle\ system
DESTDIR       = 
TARGET        = particle\ system.app/Contents/MacOS/particle\ system

####### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d particle\ system.app/Contents/MacOS/ || mkdir -p particle\ system.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: particle\ system.pro /private/tmp/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf /private/tmp/5.10.0/clang_64/mkspecs/features/spec_pre.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/qdevice.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/features/device_config.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/unix.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/mac.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/macx.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/sanitize.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/gcc-base.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/clang.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/common/clang-mac.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/qconfig.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/private/tmp/5.10.0/clang_64/mkspecs/features/qt_functions.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/qt_config.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/private/tmp/5.10.0/clang_64/mkspecs/features/exclusive_builds.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/sdk.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/toolchain.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/toolchain.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/default_pre.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/default_pre.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/resolve_config.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/default_post.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/default_post.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/objective_c.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/mac.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/warn_on.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/qt.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/resources.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/moc.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/unix/opengl.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/uic.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/unix/thread.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/qmake_use.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/file_copies.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/rez.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/testcase_targets.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/exceptions.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/yacc.prf \
		/private/tmp/5.10.0/clang_64/mkspecs/features/lex.prf \
		particle\ system.pro \
		/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/private/tmp/5.10.0/clang_64/lib/QtGui.framework/QtGui.prl \
		/private/tmp/5.10.0/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile particle\ system.pro
/private/tmp/5.10.0/clang_64/mkspecs/features/spec_pre.prf:
/private/tmp/5.10.0/clang_64/mkspecs/qdevice.pri:
/private/tmp/5.10.0/clang_64/mkspecs/features/device_config.prf:
/private/tmp/5.10.0/clang_64/mkspecs/common/unix.conf:
/private/tmp/5.10.0/clang_64/mkspecs/common/mac.conf:
/private/tmp/5.10.0/clang_64/mkspecs/common/macx.conf:
/private/tmp/5.10.0/clang_64/mkspecs/common/sanitize.conf:
/private/tmp/5.10.0/clang_64/mkspecs/common/gcc-base.conf:
/private/tmp/5.10.0/clang_64/mkspecs/common/gcc-base-mac.conf:
/private/tmp/5.10.0/clang_64/mkspecs/common/clang.conf:
/private/tmp/5.10.0/clang_64/mkspecs/common/clang-mac.conf:
/private/tmp/5.10.0/clang_64/mkspecs/qconfig.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_core.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_help.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_location.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_network.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/private/tmp/5.10.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/private/tmp/5.10.0/clang_64/mkspecs/features/qt_functions.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/qt_config.prf:
/private/tmp/5.10.0/clang_64/mkspecs/macx-clang/qmake.conf:
/private/tmp/5.10.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/private/tmp/5.10.0/clang_64/mkspecs/features/exclusive_builds.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/mac/sdk.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/toolchain.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/mac/toolchain.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/default_pre.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/mac/default_pre.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/resolve_config.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/default_post.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/mac/default_post.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/mac/objective_c.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/mac/mac.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/warn_on.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/qt.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/resources.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/moc.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/unix/opengl.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/uic.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/unix/thread.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/qmake_use.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/file_copies.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/mac/rez.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/testcase_targets.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/exceptions.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/yacc.prf:
/private/tmp/5.10.0/clang_64/mkspecs/features/lex.prf:
particle\ system.pro:
/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/private/tmp/5.10.0/clang_64/lib/QtGui.framework/QtGui.prl:
/private/tmp/5.10.0/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile particle\ system.pro

qmake_all: FORCE

particle\ system.app/Contents/PkgInfo: 
	@test -d particle\ system.app/Contents || mkdir -p particle\ system.app/Contents
	@$(DEL_FILE) particle\ system.app/Contents/PkgInfo
	@echo "APPL????" > particle\ system.app/Contents/PkgInfo
particle\ system.app/Contents/Resources/empty.lproj: 
	@test -d particle\ system.app/Contents/Resources || mkdir -p particle\ system.app/Contents/Resources
	@touch particle\ system.app/Contents/Resources/empty.lproj
	
particle\ system.app/Contents/Info.plist: 
	@test -d particle\ system.app/Contents || mkdir -p particle\ system.app/Contents
	@$(DEL_FILE) particle\ system.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.particle system,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,particle system,g" -e "s,@LIBRARY@,particle system,g" -e "s,@TYPEINFO@,????,g" /private/tmp/5.10.0/clang_64/mkspecs/macx-clang/Info.plist.app >particle\ system.app/Contents/Info.plist

all: Makefile \
		particle\ system.app/Contents/PkgInfo \
		particle\ system.app/Contents/Resources/empty.lproj \
		particle\ system.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /private/tmp/5.10.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents App.hpp $(DISTDIR)/
	$(COPY_FILE) --parents App.cpp main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r particle\ system.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /private/tmp/5.10.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h /private/tmp/5.10.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_App.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_App.cpp
moc_App.cpp: /private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		/private/tmp/5.10.0/clang_64/lib/QtCore.framework/Headers/QObject \
		/private/tmp/5.10.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		App.hpp \
		moc_predefs.h \
		/private/tmp/5.10.0/clang_64/bin/moc
	/private/tmp/5.10.0/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/private/tmp/5.10.0/clang_64/mkspecs/macx-clang -I'/Users/vpopovyc/workspace/particle system' -I'/Users/vpopovyc/workspace/particle system' -I/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers -I/private/tmp/5.10.0/clang_64/lib/QtGui.framework/Headers -I/private/tmp/5.10.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/private/tmp/5.10.0/clang_64/lib App.hpp -o moc_App.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

App.o: App.cpp App.hpp \
		/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		/private/tmp/5.10.0/clang_64/lib/QtCore.framework/Headers/QObject \
		/private/tmp/5.10.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o App.o App.cpp

main.o: main.cpp /private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		App.hpp \
		/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		/private/tmp/5.10.0/clang_64/lib/QtCore.framework/Headers/QObject \
		/private/tmp/5.10.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/private/tmp/5.10.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_App.o: moc_App.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_App.o moc_App.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

